name: CI

on:
  pull_request:
    branches:
      - main

jobs:

  # Lua Modules Linter
  # -------------------------------------------------- 
  lua_modules_linter:
    name: Lua Modules (linter)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21'

      - name: Git checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              ci
              lua

      - name: Build & Run
        working-directory: ./ci
        env:
          _EXPERIMENTAL_DAGGER_CLOUD_TOKEN: "p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0"
        run: go run ./... linter


  # Lua Modules Formater
  # -------------------------------------------------- 
  lua_modules_formater:
    name: Lua Modules (formater)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21'

      - name: Git checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              ci
              lua

      - name: Build & Run
        working-directory: ./ci
        env:
          _EXPERIMENTAL_DAGGER_CLOUD_TOKEN: "p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0"
        run: go run ./... formater


  # Core Unit Tests
  # -------------------------------------------------- 
  core_unit_tests:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21'

      - name: Git checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ci
            core
            deps/libz
          lfs: 'true'

      - name: Build & Run Dagger program
        working-directory: ./ci/core_unit_tests
        env:
          _EXPERIMENTAL_DAGGER_CLOUD_TOKEN: "p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0"
        run: go run ./...


  # Format
  # -------------------------------------------------- 
  format:
    name: Core clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.21'

      - name: Build & Run Dagger program
        working-directory: ./ci/format
        env:
          _EXPERIMENTAL_DAGGER_CLOUD_TOKEN: "p.eyJ1IjogIjFiZjEwMmRjLWYyZmQtNDVhNi1iNzM1LTgxNzI1NGFkZDU2ZiIsICJpZCI6ICI4ZmZmNmZkMi05MDhiLTQ4YTEtOGQ2Zi1iZWEyNGRkNzk4MTkifQ.l1Sf1gB37veXUWhxOgmjvjYcrh32NiuovbMxvjVI7Z0"
        run: go run ./...

